# Generated by Django 4.2.3 on 2024-10-09 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=30)),
                ('created_at', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=30)),
            ],
        ),
    ]
